/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import controller.*;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import validators.*;
/**
 *
 * @author sebas
 */
public final class Nomina extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Nomina
     */
    PreparedStatement preparedStatement = null;
    ResultSet resultSet = null;
     Connection con = BaseDeDatos.Conexion();
     DateFormat df = null;
     select s= new select(con);
     insert i=new insert(con);
     delete d= new delete(con);
     update u=new update(con);
     DefaultTableModel modelo = s.getBonus();
     DefaultTableModel modelo2 =s.getDeduccion();
     /*DefaultTableModel modelo3 =s.getTitulos();
     DefaultTableModel modelo4 =s.getDept_Emp();
     DefaultTableModel modelo5 =s.getSalarios();
     DefaultTableModel modelo6 =s.getDept_Manager();*/
     String dato= null, dato1= null,dato2= null,dato3= null,dato4= null,dato5= null;
      validator validator= new validator();
     int seleccionar;
    
    public Nomina() throws SQLException {
        initComponents();
        
        this.bonusmonth.addActionListener(this);
        this.bonusyear.addActionListener(this);
        this.deduccionmonth.addActionListener(this);
        this.deduccionyear.addActionListener(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBonus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NumeroEmpleado = new javax.swing.JTextField();
        CantidadBonus = new javax.swing.JTextField();
        TipoBonus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bonusday = new javax.swing.JComboBox<>();
        bonusmonth = new javax.swing.JComboBox<>();
        bonusyear = new javax.swing.JComboBox<>();
        Registrar = new javax.swing.JButton();
        Restablecer = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        BuscarEmpleado = new javax.swing.JButton();
        Findemployee = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Findemployee1 = new javax.swing.JTextField();
        BuscarDeduccion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDeduccion = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NumeroEmpleado1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TipoDeduccion = new javax.swing.JTextField();
        CantidadDeduccion = new javax.swing.JTextField();
        deduccionday = new javax.swing.JComboBox<>();
        deduccionmonth = new javax.swing.JComboBox<>();
        deduccionyear = new javax.swing.JComboBox<>();
        Restablecer1 = new javax.swing.JButton();
        Registrar1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        Eliminar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 600));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Registrar Bonus");

        TablaBonus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaBonus.setModel(modelo);
        TablaBonus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaBonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaBonusMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TablaBonusMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(TablaBonus);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Número de Empleado: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de Bonus:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad de Bonus:");

        NumeroEmpleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumeroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroEmpleadoActionPerformed(evt);
            }
        });

        CantidadBonus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CantidadBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadBonusActionPerformed(evt);
            }
        });

        TipoBonus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TipoBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBonusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de Bonus: ");

        bonusday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bonusday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        bonusmonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bonusmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        bonusyear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bonusyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        Registrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Restablecer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Restablecer.setText("Restablecer");
        Restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestablecerActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("Actualizar");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        BuscarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BuscarEmpleado.setText("Buscar");
        BuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update)
                        .addGap(81, 81, 81)
                        .addComponent(Eliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(NumeroEmpleado))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CantidadBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(29, 29, 29))
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(bonusday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(bonusmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(bonusyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TipoBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(Restablecer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Registrar)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Findemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(BuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Findemployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(Eliminar)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TipoBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CantidadBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bonusday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonusmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonusyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrar)
                    .addComponent(Restablecer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bonus", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Registrar Deducción");

        BuscarDeduccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BuscarDeduccion.setText("Buscar");
        BuscarDeduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDeduccionActionPerformed(evt);
            }
        });

        TablaDeduccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaDeduccion.setModel(modelo2);
        TablaDeduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaDeduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeduccionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TablaDeduccionMouseExited(evt);
            }
        });
        jScrollPane3.setViewportView(TablaDeduccion);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Número de Empleado: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de Deducción: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Cantidad de Deducción:");

        NumeroEmpleado1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumeroEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroEmpleado1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Fecha de Deducción:");

        TipoDeduccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TipoDeduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeduccionActionPerformed(evt);
            }
        });

        CantidadDeduccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CantidadDeduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadDeduccionActionPerformed(evt);
            }
        });

        deduccionday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deduccionday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        deduccionmonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deduccionmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        deduccionmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deduccionmonthActionPerformed(evt);
            }
        });

        deduccionyear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deduccionyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        Restablecer1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Restablecer1.setText("Restablecer");
        Restablecer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restablecer1ActionPerformed(evt);
            }
        });

        Registrar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Registrar1.setText("Registrar");
        Registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar1ActionPerformed(evt);
            }
        });

        update1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update1.setText("Actualizar");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        Eliminar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Eliminar1.setText("Eliminar");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumeroEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TipoDeduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadDeduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(Restablecer1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Registrar1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(deduccionday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deduccionmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deduccionyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Findemployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(BuscarDeduccion))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update1)
                        .addGap(79, 79, 79)
                        .addComponent(Eliminar1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Findemployee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarDeduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NumeroEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TipoDeduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CantidadDeduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(deduccionday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deduccionmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deduccionyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Restablecer1)
                            .addComponent(Registrar1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update1)
                    .addComponent(Eliminar1))
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Deduction", jPanel2);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Registrar Vacaciones");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Número de Empleado: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Desde:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Hasta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))))
                .addContainerGap(824, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addGap(41, 41, 41)
                .addComponent(jLabel12)
                .addGap(53, 53, 53)
                .addComponent(jLabel13)
                .addGap(53, 53, 53)
                .addComponent(jLabel14)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Holiday", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sickleave", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaBonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaBonusMouseClicked
        // TODO add your handling code here:
        seleccionar = TablaBonus.rowAtPoint(evt.getPoint());

        dato = String.valueOf(TablaBonus.getValueAt(seleccionar, 0));
        dato1 = String.valueOf(TablaBonus.getValueAt(seleccionar, 1));
        dato2 = String.valueOf(TablaBonus.getValueAt(seleccionar, 2));
        dato3 = String.valueOf(TablaBonus.getValueAt(seleccionar, 3));
        

    }//GEN-LAST:event_TablaBonusMouseClicked

    private void TablaBonusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaBonusMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_TablaBonusMouseExited

    private void NumeroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroEmpleadoActionPerformed

    private void CantidadBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadBonusActionPerformed

    private void TipoBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBonusActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed

        var errores=validator.Bonus(NumeroEmpleado.getText(),CantidadBonus.getText(),TipoBonus.getText());
        String txt=" ";
        for (String error:errores) {
            txt=txt+error+"\n";
        }
        if (!txt.equals(" ")) {

            JOptionPane.showMessageDialog(null, txt);

        }else{
            try {
                // TODO add your handling code here:
                df = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
                String birth_date = bonusyear.getSelectedItem().toString() + "-" + (bonusmonth.getSelectedIndex()+1) + "-" + bonusday.getSelectedItem().toString();

                Date det = df.parse(birth_date);
                java.sql.Date sqdet = new java.sql.Date(det.getTime());

                System.out.println(sqdet);

                i.setBonus(NumeroEmpleado.getText(),sqdet, CantidadBonus.getText(), TipoBonus.getText());
                modelo=s.getBonus();

                TablaBonus.setModel(modelo);
                modelo.fireTableDataChanged();

                System.out.println("Se realizo el registro");

            } catch (ParseException ex) {
                Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void RestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestablecerActionPerformed
        // TODO add your handling code here:
        NumeroEmpleado.setText("");
        CantidadBonus.setText("");
        bonusday.setSelectedIndex(0);
        bonusmonth.setSelectedIndex(0);
        bonusyear.setSelectedIndex(0);
        TipoBonus.setText("");
        Findemployee.setText("");
    }//GEN-LAST:event_RestablecerActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        /*try {
            u.updateEmpleados(dato,java.sql.Date.valueOf(dato1) , dato2, dato3, dato4, java.sql.Date.valueOf(dato5));
            /*try {
                // TODO add your handling code here:
                int fila = TablaEmpleados.getRowCount();
                for (int i = fila; i >=0; i++) {
                    modelo.removeRow(i);
                }
                getEmpleados();
            } catch (SQLException ex) {
                Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParseException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_updateActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try {
            if (dato.equals(d.setDeleteBonus(dato)[0])) {
                int fila = TablaBonus.getSelectedRow();
                
                if (fila >= 0) {
                    modelo.removeRow(fila);
                    JOptionPane.showMessageDialog(null, "Se elimino el Bonus");
                    dato=null;
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(Nomina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Nomina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void BuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEmpleadoActionPerformed
        try {
            // TODO add your handling code here:
            if (Findemployee.getText().isEmpty()) {
                modelo =s.getBonus();
                TablaDeduccion.setModel(modelo);
            }else{

                modelo =s.FindEmpleadosB(Integer.parseInt(Findemployee.getText()));
                TablaDeduccion.setModel(modelo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarEmpleadoActionPerformed

    private void BuscarDeduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDeduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDeduccionActionPerformed

    private void TablaDeduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeduccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDeduccionMouseClicked

    private void TablaDeduccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeduccionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDeduccionMouseExited

    private void NumeroEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroEmpleado1ActionPerformed

    private void TipoDeduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeduccionActionPerformed

    private void CantidadDeduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadDeduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadDeduccionActionPerformed

    private void deduccionmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deduccionmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deduccionmonthActionPerformed

    private void Restablecer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restablecer1ActionPerformed
        // TODO add your handling code here:
        NumeroEmpleado1.setText("");
        CantidadBonus.setText("");
        deduccionday.setSelectedIndex(0);
        deduccionmonth.setSelectedIndex(0);
        deduccionyear.setSelectedIndex(0);
        TipoDeduccion.setText("");
        Findemployee1.setText("");
        
    }//GEN-LAST:event_Restablecer1ActionPerformed

    private void Registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registrar1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Eliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Nomina().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Nomina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarDeduccion;
    private javax.swing.JButton BuscarEmpleado;
    private javax.swing.JTextField CantidadBonus;
    private javax.swing.JTextField CantidadDeduccion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JTextField Findemployee;
    private javax.swing.JTextField Findemployee1;
    private javax.swing.JTextField NumeroEmpleado;
    private javax.swing.JTextField NumeroEmpleado1;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Registrar1;
    private javax.swing.JButton Restablecer;
    private javax.swing.JButton Restablecer1;
    private javax.swing.JTable TablaBonus;
    private javax.swing.JTable TablaDeduccion;
    private javax.swing.JTextField TipoBonus;
    private javax.swing.JTextField TipoDeduccion;
    private javax.swing.JComboBox<String> bonusday;
    private javax.swing.JComboBox<String> bonusmonth;
    private javax.swing.JComboBox<String> bonusyear;
    private javax.swing.JComboBox<String> deduccionday;
    private javax.swing.JComboBox<String> deduccionmonth;
    private javax.swing.JComboBox<String> deduccionyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
    if (e.getSource() == bonusmonth) {
        
            int days = 31;
            System.out.println("months");
            if (bonusmonth.getSelectedItem().toString().equals("Enero")) {
               days = 32;
               System.out.println("january");

            }
            if (bonusmonth.getSelectedItem().toString().equals("Febrero")) {
               if (Integer.parseInt(bonusyear.getSelectedItem().toString()) % 4 == 0) {
                  days = 30;
               } else {
                  days = 29;
               }

            }
            if (bonusmonth.getSelectedItem().toString().equals("Marzo")) {
               days = 32;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Abril")) {
               days = 31;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Mayo")) {
               days = 32;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Junio")) {
               days = 31;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Julio")) {
               days = 32;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Agosto")) {
               days = 32;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Septiembre")) {
               days = 31;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Octubre")) {
               days = 32;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Noviembre")) {
               days = 31;
            }
            if (bonusmonth.getSelectedItem().toString().equals("Diciembre")) {
               days = 32;
            }
            bonusday.removeAllItems();
            for (int i = 1; i < days; i++) {
               bonusday.addItem("" + i);
            }
         } else if (e.getSource() == bonusyear) {
            int days = bonusday.getItemCount() + 1;
            if (bonusmonth.getSelectedItem().toString().equals("Febrero")) {
               if (Integer.parseInt(bonusyear.getSelectedItem().toString()) % 4 == 0) {
                  days = 30;
               } else {
                  days = 29;
               }

            }
            bonusday.removeAllItems();
            for (int i = 1; i < days; i++) {
               bonusday.addItem("" + i);
            }
         }
        if (e.getSource() == deduccionmonth) {
        
            int days = 31;
            System.out.println("months");
            if (deduccionmonth.getSelectedItem().toString().equals("Enero")) {
               days = 32;
               System.out.println("january");

            }
            if (deduccionmonth.getSelectedItem().toString().equals("Febrero")) {
               if (Integer.parseInt(deduccionyear.getSelectedItem().toString()) % 4 == 0) {
                  days = 30;
               } else {
                  days = 29;
               }

            }
            if (deduccionmonth.getSelectedItem().toString().equals("Marzo")) {
               days = 32;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Abril")) {
               days = 31;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Mayo")) {
               days = 32;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Junio")) {
               days = 31;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Julio")) {
               days = 32;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Agosto")) {
               days = 32;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Septiembre")) {
               days = 31;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Octubre")) {
               days = 32;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Noviembre")) {
               days = 31;
            }
            if (deduccionmonth.getSelectedItem().toString().equals("Diciembre")) {
               days = 32;
            }
            deduccionday.removeAllItems();
            for (int i = 1; i < days; i++) {
               deduccionday.addItem("" + i);
            }
         } else if (e.getSource() == deduccionyear) {
            int days = deduccionday.getItemCount() + 1;
            if (deduccionmonth.getSelectedItem().toString().equals("Febrero")) {
               if (Integer.parseInt(deduccionyear.getSelectedItem().toString()) % 4 == 0) {
                  days = 30;
               } else {
                  days = 29;
               }

            }
            deduccionday.removeAllItems();
            for (int i = 1; i < days; i++) {
               deduccionday.addItem("" + i);
            }
         }
    }
}
